### ISSUE TITLE
Storybook導入

### ISSUE THREAD

**Issue by rkun123** [Kyutech-C3/web#2]
コンポーネント単体で確認できるように、Storybookの導入ができたら幸せになれそう

**Comment by rkun123** [comment]
ついでにciでビルドしてGitHub pagesでホスティングできたら神

**Comment by Simo-C3** [comment]
確かに！
明日やってみます

**Comment by Simo-C3** [comment]
ストーリーブックはいろいろと面倒が多いので導入を見送ります
